initial_position:
  x: -1.0
  y: 1.0
  yaw: deg(90)
goal_position:
  x: 0.5
  y: -0.5
  yaw: deg(90)
distance: 1.5
ang_param:
  kp: 1.5
  ki: 0.0
  kd: 0.0
lin_param:
  kp: 1.0
  ki: 0.0
  kd: 0.0
tb3_0_status: "idle"
tb3_0_1step: false
tb3_1_status: "idle"
tb3_1_1step: false