initial_position: [2.0, 0.0, deg(0)]
goal_position: [6.0, -1]
intermediate_points:
  - [4.0, -1.0]
  # - [6.0, 3.0]
  # - [10.0, 2.0]
  # - [10.0,-1.0]
  # - [6.0, -2.0]
distance: 1
ang_param:
  kp: 1.5
  ki: 0.0
  kd: 0.0
lin_param:
  kp: 1.0
  ki: 0.0
  kd: 0.0